name: Build_ImageBuilder

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          选择 OpenWrt 分支
        required: true
        default: "immortalwrt"
        type: choice
        options:
          - immortalwrt
          - openwrt
          
      image:
        description: |
          选择 imageBuilder 镜像
        required: true
        default: "rockchip-armv8"
        type: choice
        options:
          - x86-64
          - rockchip-armv8
          
      version:
        description: |
          选择 OpenWrt 版本
        required: true
        default: "24.10.5"
        type: choice
        options:
          - "24.10-SNAPSHOT"
          - "24.10.5"
          - "24.10.4"
          - "24.10.3"
          - "24.10.2"
          - "24.10.1"
          - "24.10.0"
          - "23.05.5"
      
      profile:
        description: |
          输入 软路由型号 可选值如下：
        required: true
        default: 'nanopi-r6s'
        type: choice
        options:
          - nanopi-r6s
          - orangepi-5plus
          - x86-64
          
      rootfs_partsize:
        description: |
          设置软件包大小 单位(MB)
        required: true
        default: '1024'
        type: choice
        options:
          - 512
          - 1024
          - 2048
      
      network_lan:
        description: |
          设置固件IP地址
        required: true
        default: '10.10.10.254'
        type: choice
        options:
          - "10.10.10.254"
          - "192.168.100.1"
          
      docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: false
        type: boolean
        
      enable_pppoe:
        description: |
          是否默认PPPoE协议?
        required: true
        default: true
        type: boolean
        
      pppoe_account:
        description: |
          是否添加 宽带账号? (可留空)
        required: false
        default: '123'
      pppoe_password:
        description: |
          是否添加 宽带密码? (可留空)
        required: false
        default: '123'
        
      diy_package:
        description: |
          设置Diy插件网址
        required: true
        default: 'all'
        type: choice
        options:
          - name: nanopi-r6s
            package: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_env/nanopi-r6s.env"
            script: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_files/nanopi-r6s.sh"
          - name: orangepi-5plus
            package: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_env/orangepi-5plus.env"
            script: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_env/orangepi-5plus.sh"
          - name: x86-64
            package: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_env/x86-64.env"
            script: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/diy_env/x86-64.sh"
    
jobs:
  Call_ImageBuilder:
    uses: ./.github/workflows/Call_ImageBuilder.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      image: ${{ inputs.image }}
      version: ${{ inputs.version }}
      profile: ${{ inputs.profile }}
      rootfs_partsize: ${{ inputs.rootfs_partsize }}
      network_lan: ${{ inputs.network_lan }}
      docker: ${{ inputs.docker }}
      enable_pppoe: ${{ inputs.enable_pppoe }}
      pppoe_account: ${{ inputs.pppoe_account }}
      pppoe_password: ${{ inputs.pppoe_password }}
      diy_package: ${{ inputs.diy_package }}
      diy_script: ${{ inputs.diy_script }}