name: Build_ImageBuilder-Box

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          选择 OpenWrt 分支
        required: true
        default: "immortalwrt"
        type: choice
        options:
          - immortalwrt
          - openwrt
          
      version:
        description: |
          选择 OpenWrt 版本
        required: true
        default: "24.10.5"
        type: choice
        options:
          - "24.10-SNAPSHOT"
          - "24.10.5"
          - "24.10.4"
          - "24.10.3"
          - "24.10.2"
          - "24.10.1"
          - "24.10.0"
          - "23.05.5"
      
      openwrt_board:
        description: |
          选择 设备 可选值如下：
        required: false
        default: "wxy-oect"
        type: choice
        options:
          - all
          - orangepi-5-plus
          - wxy-oect
          - s905d
      
      openwrt_kernel:
        description: |
          选择内核版本：
        required: false
        default: "6.1.y_6.12.y"
        type: choice
        options:
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 6.18.y
          - 5.10.y_5.15.y
          - 6.1.y_6.6.y
          - 6.12.y_6.18.y
          - 6.1.y_6.12.y
          - 6.1.y_6.18.y
      
      auto_kernel:
        description: "自动使用最新内核"
        required: false
        default: true
        type: boolean
      
      builder_name:
        description: "设置OpenWrt构建签名"
        required: false
        default: "3wlh"
        type: choice
        options:
          - "3wlh"
          - "ophub"
          - "angel"
          - "yourname"
          
      rootfs_partsize:
        description: |
          设置软件包大小 单位(MB)
        required: true
        default: '1024'
        type: choice
        options:
          - 512
          - 1024
          - 2048
      
      network_lan:
        description: |
          设置固件IP地址
        required: true
        default: '10.10.10.250'
        type: choice
        options:
          - "10.10.10.254"
          - "192.168.100.1"
          - "10.10.10.250"
          - "10.10.10.5"
      
      diy_package:
        description: |
          设置Diy插件网址
        required: true
        default: 'all'
        type: choice
        options:
          - "diy_env/wxy-oect.env"
          - "diy_env/armsr-5plus.env"
          
      diy_script:
        description: |
          设置Diy初始化脚本网址
        required: true
        default: 'all'
        type: choice
        options:
          - "diy_files/wxy-oect.sh"
          - "orangepi-5plus.sh"
      
      diy_download:
        description: |
          下载自定义插件
        required: true
        default: 'all'
        type: choice
        options:
          - "all"
          - "diy_download/aarch64.txt"
          - "diy_download/x86-64.txt"
         
      docker:
        description: |
          是否编译 Docker 插件
        required: true
        default: false
        type: boolean
        
      service:
        description: "编译成网络服务固件"
        required: false
        default: true
        type: boolean
      
env:
  UPLOAD_BIN_DIR: false
  PATH_CACHE: /tmp/.cache
  CACHE_IMAGE: imagebuilder:armsr-armv8-${{ inputs.version }}.tar

jobs:
  Build:
    name: Build ${{ inputs.branch }}-${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure docker image
        run: |
          if [[ "${{ inputs.version }}" =~ "SNAPSHOT" || "${{ inputs.branch }}" == "openwrt" ]]; then
            IMAGE=armsr-armv8-${{ inputs.version }}
          else
            IMAGE=armsr-armv8-openwrt-${{ inputs.version }}
          fi
          if [[ "${{ inputs.branch }}" == "openwrt" ]]; then
            echo "builder=/builder" >> $GITHUB_ENV
          else
            echo "builder=/home/build/immortalwrt" >> $GITHUB_ENV
          fi
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "CACHE_KEY=${{ inputs.branch }}-${IMAGE}-$(echo "${IMAGE}" | md5sum | awk '{print $1}')" >> $GITHUB_ENV
      
      - name: Download Config Data
        env:
          regexper: '^(https?)://[a-zA-Z0-9.-]+\.[a-zA-Z0-9]{1,}(:[0-9]{1,5})?(/[^/]*)*$'
        run: |
          # 下载配置数据
          test -d "$(pwd)/diy_config" || mkdir -p "$(pwd)/diy_config"
          if grep -qE "$regexper" <<< "${{ inputs.diy_package }}"; then
            wget -q ${{ inputs.diy_package }} -O "$(pwd)/diy_config/diy_pkg.env"
          else
            [[ "${{ inputs.diy_package }}" != "all" ]] && \
            cp -f ${{ inputs.diy_package }} "$(pwd)/diy_config/diy_pkg.env"
          fi
          if grep -qE "$regexper" <<< "${{ inputs.diy_script }}"; then
            wget -q ${{ inputs.diy_script }} -O "$(pwd)/diy_config/defaults.sh"
          else
            [[ "${{ inputs.diy_script }}" != "all" ]] && \
            cp -f ${{ inputs.diy_script }} "$(pwd)/diy_config/defaults.sh"
          fi
          if grep -qE "$regexper" <<< "${{ inputs.diy_download }}"; then
            wget -q ${{ inputs.diy_download }} -O "$(pwd)/diy_config/url"
          else
            [[ "${{ inputs.diy_download }}" != "all" ]] && \
            cp -f ${{ inputs.diy_download }} "$(pwd)/diy_config/url"
          fi
              
      - name: Enable Cache
        uses: actions/cache@main
        with:
          path: ${{ env.PATH_CACHE }}
          key: ${{ env.CACHE_KEY }}
          
      - name: Configure environment variables
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "time=$(date "+%Y.%m.%d-%H%M%S")" >> $GITHUB_ENV
             
      - name: Create Edit info
        run: |
          echo "## 编译时间：\`${{ env.time }}\`" > info.md
          echo "## [![Github](https://img.shields.io/badge/Release文件可在国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge)](https://ghproxy.net/)" >> info.md
          echo "## 固件信息：" >> info.md
          echo "* 固件版本 \`${{ inputs.version }}\`" >> info.md
          echo "* 固件地址 \`${{ inputs.network_lan }}\`" >> info.md
          echo "* 用户名 \`root\` 密码：无" >> info.md
          echo "* 默认软件包大小 \`${{ inputs.rootfs_partsize }}MB\`" >> info.md
          if [[ "${{ inputs.docker }}" == "true" ]]; then
            echo "* 添加\`docker\`版本" >> info.md
          fi
          
      - name: Set executable permissions
        env: 
          URL: "https://raw.githubusercontent.com/3wlh/Actions-ImageaBuilder/refs/heads/main/make/armsr"
        run: wget -q "${URL}/make.sh" -O "$(pwd)/make.sh" && chmod -R 755 "$(pwd)/make.sh"
      
      - name: Check Docker images
        run: |
          mkdir -p ${{ env.PATH_CACHE }}/image
          if [[ -f "${{ env.PATH_CACHE }}/image/${{ env.CACHE_IMAGE }}" ]]; then
            echo -e "\e[1;32mImport Docker image：${{ env.CACHE_IMAGE }}\e[0m"
            docker load --input \
            ${{ env.PATH_CACHE }}/image/${{ env.CACHE_IMAGE }}
          else
            docker pull ${{ inputs.branch }}/imagebuilder:${{ env.IMAGE }}
            echo -e "\e[1;32mExport the image to the cache directory\e[0m"
            docker save --output \
            ${{ env.PATH_CACHE }}/image/${{ env.CACHE_IMAGE }} \
            ${{ inputs.branch }}/imagebuilder:${{ env.IMAGE }}
          fi
          chmod -R 755 "${{ env.PATH_CACHE }}"
      
      - name: Generate Env File
        run: |
          # 动态生成 .env 文件
          cat > .env << EOF
          PROFILES=${{ inputs.openwrt_board }}
          SERVICE=${{ inputs.service }}
          BRANCH=${{ inputs.branch }}
          VERSION=${{ inputs.version }}
          INCLUDE_DOCKER=${{ inputs.docker }}
          NETWORK_LAN=${{ inputs.network_lan }}
          ENABLE_PPPOE=${{ inputs.enable_pppoe }}
          PPPOE_ACCOUNT=${{ inputs.pppoe_account }}
          PPPOE_PASSWORD=${{ inputs.pppoe_password }}
          ROOTFS_PARTSIZE=${{ inputs.rootfs_partsize }}
          EOF
       
      - name: Building ${{ inputs.branch }} armsr-armv8
        id: building
        run: |
          docker run --rm -i \
            --user root \
            --env-file .env \
            -v "${{ env.PATH_CACHE }}/dl:${{ env.builder }}/dl" \
            -v "${{ env.PATH_CACHE }}/packages:${{ env.builder }}/packages" \
            -v "${{ github.workspace }}/armsr-armv8/bin:${{ env.builder }}/bin" \
            -v "${{ github.workspace }}/diy_config:${{ env.builder }}/diy_config" \
            -v "${{ github.workspace }}/make.sh:${{ env.builder }}/make.sh" \
            ${{ inputs.branch }}/imagebuilder:${{ env.IMAGE }} /bin/bash ${{ env.builder }}/make.sh
          cat "${{ github.workspace }}/armsr-armv8/bin/.bashrc" 2>/dev/null >> $GITHUB_OUTPUT
          #cat "${{ github.workspace }}/armsr-armv8/bin/.bashrc" 2>/dev/null >> $GITHUB_ENV
          # exit 1
      
      - name: Query Cleanup Cache
        if: steps.building.outputs.cache == 'delete'
        run: |
          # List caches for current repository
          gh cache list
          # Delete a cache by key
          if [[ "$(gh cache list)" =~ "${{ env.CACHE_KEY }}"  ]]; then
            gh cache delete ${{ env.CACHE_KEY }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Reload again Cache
        if: steps.building.outputs.cache == 'delete'
        uses: actions/cache@main
        with:
          path: ${{ env.PATH_CACHE }}
          key: ${{ env.CACHE_KEY }}   
      
      - name: Upload bin directory
        uses: actions/upload-artifact@main
        if: steps.building.outputs.building == 'success' && env.UPLOAD_BIN_DIR == 'true'
        with:
          name: GitHub-Actions_armsr-armv8
          path: ${{ env.PATH_CACHE }}/dl
      
      - name: Generate Firmware SHA-256
        if: steps.building.outputs.building == 'success'
        id: images
        run: |
          mkdir -p ${{ github.workspace }}/output && cd ${{ github.workspace }}/output
          find ${{ github.workspace }}/armsr-armv8/bin/targets/ -type f -name "*.tar.gz" -exec cp {} ${{ github.workspace }}/output \;
          cp ${{ github.workspace }}/armsr-armv8/bin/*.conf* ${{ github.workspace }}/output
          for file in *.tar.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
          echo "status=success" >> $GITHUB_OUTPUT
      
      - name: Upload ${{ inputs.branch }} as release assets
        if: steps.images.outputs.status == 'success'
        uses: ncipollo/release-action@main
        with:
          tag: GitHub-Actions_${{ inputs.branch }}-${{ inputs.openwrt_board }}
          name: ${{ inputs.branch }}_Box-${{ inputs.openwrt_board }}
          artifacts: ${{ github.workspace }}/output/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: info.md
          
      - name: Packaging OpenWrt ophub
        if: steps.images.outputs.status == 'success'
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: output/*.tar.gz
          openwrt_board: ${{ inputs.openwrt_board }}
          openwrt_kernel: ${{ inputs.openwrt_kernel }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ophub/kernel
          kernel_usage: stable
          builder_name: ${{ inputs.builder_name }}
          openwrt_size: 256/${{ inputs.rootfs_partsize }}
          
      - name: Generate Ophub Firmware SHA-256
        if: env.PACKAGED_STATUS == 'success'
        run: |
          cd ${{ env.PACKAGED_OUTPUTPATH }}
          name=$(find . -type f -name "*.img.gz" -exec basename {} .img.gz \;| sed "s|openwrt||")
          if [[ "${{ inputs.service }}" == "true"  ]]; then
            cp *.img.gz ${{ github.workspace }}/output/${{ inputs.branch }}${name}-service.img.gz
          else
            cp *.img.gz ${{ github.workspace }}/output/${{ inputs.branch }}${name}.img.gz
          fi
          cd ${{ github.workspace }}/output
          for file in *.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done
      
      - name: Delete GitHub Release
        if: env.PACKAGED_STATUS == 'success'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ inputs.branch }}-${{ inputs.openwrt_board }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload the packaged OpenWrt
        if: env.PACKAGED_STATUS == 'success'
        uses: ncipollo/release-action@main
        with:
          tag: GitHub-Actions_${{ inputs.branch }}-${{ inputs.openwrt_board }}
          name: ${{ inputs.branch }}_Box-${{ inputs.openwrt_board }}
          artifacts: ${{ github.workspace }}/output/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: info.md       